server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eventstore
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
